"""add_depfix_api_keys_and_github_token

Revision ID: ab1859e42d09
Revises: 
Create Date: 2026-03-11 13:31:50.650902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab1859e42d09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('pypi_url', sa.String(length=500), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('latest_version', sa.String(length=50), nullable=True),
    sa.Column('last_version_check', sa.DateTime(), nullable=True),
    sa.Column('docs_cache', sa.JSON(), nullable=True),
    sa.Column('docs_cached_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_created_at'), 'dependencies', ['created_at'], unique=False)
    op.create_index(op.f('ix_dependencies_is_active'), 'dependencies', ['is_active'], unique=False)
    op.create_index(op.f('ix_dependencies_name'), 'dependencies', ['name'], unique=True)
    op.create_table('user_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ollama_url', sa.String(length=500), nullable=True),
    sa.Column('postgres_url', sa.String(length=500), nullable=True),
    sa.Column('github_token', sa.String(length=500), nullable=True),
    sa.Column('gitlab_token', sa.String(length=500), nullable=True),
    sa.Column('gitlab_url', sa.String(length=500), nullable=True),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.String(length=10), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('preferred_quantization', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_config_user_id'), 'user_config', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=True),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depfix_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depfix_api_keys_is_active'), 'depfix_api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_depfix_api_keys_user_id'), 'depfix_api_keys', ['user_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('primary_error_type', sa.String(length=255), nullable=True),
    sa.Column('primary_error_category', sa.String(length=255), nullable=True),
    sa.Column('extracted_errors', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_is_processed'), 'logs', ['is_processed'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_table('setup_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('selected_dependencies', sa.JSON(), nullable=True),
    sa.Column('phase1_completed', sa.Boolean(), nullable=True),
    sa.Column('phase2_completed', sa.Boolean(), nullable=True),
    sa.Column('embeddings_status', sa.String(length=50), nullable=True),
    sa.Column('github_gitlab_connected', sa.Boolean(), nullable=True),
    sa.Column('phase3_completed', sa.Boolean(), nullable=True),
    sa.Column('rag_ready', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vector_stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('vector_db_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_stores_collection_name'), 'vector_stores', ['collection_name'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_intent', sa.String(length=50), nullable=True),
    sa.Column('query_intent_category', sa.String(length=50), nullable=True),
    sa.Column('selected_dependencies', sa.JSON(), nullable=True),
    sa.Column('retrieved_docs', sa.JSON(), nullable=True),
    sa.Column('retrieval_scores', sa.JSON(), nullable=True),
    sa.Column('generated_response', sa.Text(), nullable=True),
    sa.Column('response_quality', sa.String(length=50), nullable=True),
    sa.Column('is_response_approved', sa.Boolean(), nullable=True),
    sa.Column('suggested_fixes', sa.JSON(), nullable=True),
    sa.Column('accepted_fix', sa.JSON(), nullable=True),
    sa.Column('fix_executed', sa.Boolean(), nullable=True),
    sa.Column('fix_result', sa.JSON(), nullable=True),
    sa.Column('is_evaluated', sa.Boolean(), nullable=True),
    sa.Column('evaluation_score', sa.String(length=50), nullable=True),
    sa.Column('evaluation_feedback', sa.Text(), nullable=True),
    sa.Column('evaluation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_created_at'), 'queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_queries_user_id'), 'queries', ['user_id'], unique=False)
    op.create_table('query_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_dependencies_dependency_id'), 'query_dependencies', ['dependency_id'], unique=False)
    op.create_index(op.f('ix_query_dependencies_query_id'), 'query_dependencies', ['query_id'], unique=False)
    op.drop_index(op.f('doc_chunks_dep_idx'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dependency_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.create_index(op.f('doc_chunks_dep_idx'), 'document_chunks', ['dependency_name'], unique=False)
    op.drop_index(op.f('ix_query_dependencies_query_id'), table_name='query_dependencies')
    op.drop_index(op.f('ix_query_dependencies_dependency_id'), table_name='query_dependencies')
    op.drop_table('query_dependencies')
    op.drop_index(op.f('ix_queries_user_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_created_at'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_vector_stores_collection_name'), table_name='vector_stores')
    op.drop_table('vector_stores')
    op.drop_table('setup_status')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_is_processed'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_depfix_api_keys_user_id'), table_name='depfix_api_keys')
    op.drop_index(op.f('ix_depfix_api_keys_is_active'), table_name='depfix_api_keys')
    op.drop_table('depfix_api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_config_user_id'), table_name='user_config')
    op.drop_table('user_config')
    op.drop_index(op.f('ix_dependencies_name'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_is_active'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_created_at'), table_name='dependencies')
    op.drop_table('dependencies')
    # ### end Alembic commands ###
